import { createServer } from "node:http";
import { readFile, mkdir } from "node:fs/promises";
import { extname, join, normalize } from "node:path";
import { fileURLToPath } from "node:url";
import { randomBytes, randomUUID, createHash, scrypt as scryptCallback, timingSafeEqual } from "node:crypto";
import { promisify } from "node:util";
import { DatabaseSync } from "node:sqlite";
const scrypt=promisify(scryptCallback),root=fileURLToPath(new URL(".",import.meta.url)),dataDir=join(root,"data");await mkdir(dataDir,{recursive:true});const db=new DatabaseSync(join(dataDir,"palatlas.sqlite"));
const types={".html":"text/html; charset=utf-8",".js":"text/javascript; charset=utf-8",".css":"text/css; charset=utf-8",".json":"application/json",".csv":"text/csv; charset=utf-8",".webmanifest":"application/manifest+json"};
const sources=[{source:"Pocketpair",title:"Noticias oficiales de Palworld",url:"https://www.pocketpair.jp/news/"},{source:"Palworld EN",title:"Cuenta oficial en X",url:"https://x.com/Palworld_EN"},{source:"Palworld JP",title:"Cuenta oficial en X (日本語)",url:"https://x.com/Palworld_JP"}];
db.exec(`CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,created_at TEXT NOT NULL);CREATE TABLE IF NOT EXISTS sessions(token_hash TEXT PRIMARY KEY,user_id TEXT NOT NULL,expires_at INTEGER NOT NULL);CREATE TABLE IF NOT EXISTS sync_state(user_id TEXT PRIMARY KEY,payload TEXT NOT NULL,updated_at TEXT NOT NULL);CREATE TABLE IF NOT EXISTS password_resets(token_hash TEXT PRIMARY KEY,user_id TEXT NOT NULL,expires_at INTEGER NOT NULL);`);
const json=(res,status,value)=>{res.writeHead(status,{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"});res.end(JSON.stringify(value))};async function body(req){let text="";for await(const chunk of req)text+=chunk;return text?JSON.parse(text):{}}async function hash(password,salt=randomBytes(16).toString("hex")){const key=await scrypt(password,salt,64);return `${salt}:${key.toString("hex")}`}async function verify(password,stored){const [salt,hex]=String(stored).split(":");const actual=await scrypt(password,salt,64),expected=Buffer.from(hex,"hex");return expected.length===actual.length&&timingSafeEqual(actual,expected)}const digest=value=>createHash("sha256").update(value).digest("hex");
const limits=new Map();function limited(req,key){const now=Date.now(),ip=req.socket.remoteAddress||"unknown",id=`${ip}:${key}`,item=limits.get(id)||{at:now,count:0};if(now-item.at>60000){item.at=now;item.count=0}item.count++;limits.set(id,item);return item.count>30}
function auth(req){const raw=String(req.headers.authorization||"").replace(/^Bearer\s+/i,"");if(!raw)return null;const row=db.prepare("SELECT users.id,users.email,sessions.expires_at FROM sessions JOIN users ON users.id=sessions.user_id WHERE sessions.token_hash=?").get(digest(raw));if(!row||row.expires_at<Date.now())return null;return {id:row.id,email:row.email}}
function issue(userId){const raw=randomBytes(32).toString("hex");db.prepare("INSERT INTO sessions(token_hash,user_id,expires_at) VALUES(?,?,?)").run(digest(raw),userId,Date.now()+30*24*60*60*1000);return raw}
createServer(async(req,res)=>{try{const url=new URL(req.url,"http://localhost");if(limited(req,url.pathname))return json(res,429,{error:"Demasiadas solicitudes; inténtalo más tarde."});if(url.pathname==="/api/news")return json(res,200,sources.map(item=>({...item,date:new Date().toISOString()})));
if(url.pathname==="/api/auth/register"&&req.method==="POST"){const v=await body(req),email=String(v.email||"").trim().toLowerCase(),password=String(v.password||"");if(!/^\S+@\S+\.\S+$/.test(email)||password.length<8)return json(res,400,{error:"Email o contraseña no válidos"});if(db.prepare("SELECT id FROM users WHERE email=?").get(email))return json(res,409,{error:"La cuenta ya existe"});const id=randomUUID();db.prepare("INSERT INTO users VALUES(?,?,?,?)").run(id,email,await hash(password),new Date().toISOString());return json(res,201,{token:issue(id),user:{id,email}})}
if(url.pathname==="/api/auth/login"&&req.method==="POST"){const v=await body(req),email=String(v.email||"").trim().toLowerCase(),user=db.prepare("SELECT * FROM users WHERE email=?").get(email);if(!user||!(await verify(String(v.password||""),user.password_hash)))return json(res,401,{error:"Credenciales incorrectas"});return json(res,200,{token:issue(user.id),user:{id:user.id,email:user.email}})}
if(url.pathname==="/api/auth/logout"&&req.method==="POST"){const raw=String(req.headers.authorization||"").replace(/^Bearer\s+/i,"");db.prepare("DELETE FROM sessions WHERE token_hash=?").run(digest(raw));return json(res,200,{ok:true})}
if(url.pathname==="/api/auth/me"&&req.method==="GET"){const user=auth(req);return user?json(res,200,{user:{id:user.id,email:user.email}}):json(res,401,{error:"No autenticado"})}
if(url.pathname==="/api/auth/request-reset"&&req.method==="POST"){const v=await body(req),email=String(v.email||"").trim().toLowerCase(),user=db.prepare("SELECT id FROM users WHERE email=?").get(email);if(!user)return json(res,200,{ok:true});const raw=randomBytes(32).toString("hex");db.prepare("INSERT INTO password_resets VALUES(?,?,?)").run(digest(raw),user.id,Date.now()+15*60*1000);return json(res,200,{ok:true,resetToken:raw})}
if(url.pathname==="/api/auth/reset"&&req.method==="POST"){const v=await body(req),row=db.prepare("SELECT * FROM password_resets WHERE token_hash=?").get(digest(String(v.token||"")));if(!row||row.expires_at<Date.now()||String(v.password||"").length<8)return json(res,400,{error:"Token o contraseña no válidos"});db.prepare("UPDATE users SET password_hash=? WHERE id=?").run(await hash(v.password),row.user_id);db.prepare("DELETE FROM password_resets WHERE token_hash=?").run(row.token_hash);return json(res,200,{ok:true})}
if(url.pathname==="/api/sync"){const user=auth(req);if(!user)return json(res,401,{error:"Necesitas iniciar sesión"});if(req.method==="GET"){const row=db.prepare("SELECT payload,updated_at FROM sync_state WHERE user_id=?").get(user.id);return json(res,200,row?{...JSON.parse(row.payload),syncedAt:row.updated_at}:null)}if(req.method==="POST"){const payload=JSON.stringify(await body(req)),now=new Date().toISOString();db.prepare("INSERT INTO sync_state(user_id,payload,updated_at) VALUES(?,?,?) ON CONFLICT(user_id) DO UPDATE SET payload=excluded.payload,updated_at=excluded.updated_at").run(user.id,payload,now);return json(res,200,{...JSON.parse(payload),syncedAt:now})}}
const relative=url.pathname==="/"?"index.html":url.pathname.slice(1),file=normalize(join(root,relative));if(!file.startsWith(root))throw new Error("Invalid path");res.writeHead(200,{"Content-Type":types[extname(file)]??"application/octet-stream"});res.end(await readFile(file));}catch(error){json(res,400,{error:"Solicitud no válida"})}}).listen(Number(process.env.PORT||4173),process.env.HOST||"127.0.0.1",()=>console.log("PalAtlas disponible en http://localhost:4173"));