import { pals, materials, levelMilestones, calculateBreeding, officialNewsSources, loadVersionedDataset } from "../src/index.js";
let catalog=pals, datasetCombos=[]; const root=document.querySelector("#root"), state={view:"paldex",query:"",checklist:JSON.parse(localStorage.getItem("palatlas-checklist")||"{}")};
const save=()=>localStorage.setItem("palatlas-checklist",JSON.stringify(state.checklist)); const esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
function head(title,kicker,body,stats=""){root.innerHTML=`<section class="hero"><div><div class="kicker">${kicker}</div><h1>${title}</h1><p>Todo lo que necesitas para llevar tu partida un paso más allá.</p></div>${stats}</section>${body}`;document.querySelector("#section").textContent=state.view.toUpperCase()}
function card(p){let on=state.checklist[p.id], icon=p.types.includes("Fuego")?"🔥":p.types.includes("Agua")?"💧":p.types.includes("Planta")?"🌿":p.types.includes("Oscuridad")?"🌙":"✦";return `<article class="card ${on?"checked":""}"><button class="check" data-id="${p.id}">✓</button><span class="num">#${String(p.number).padStart(3,"0")}</span><div class="orb">${icon}</div><h3>${esc(p.name)}</h3>${p.types.map(t=>`<span class="tag">${esc(t)}</span>`).join("")}<p class="num" style="margin-top:12px">${(p.passives||[]).length} pasiva(s)</p></article>`}
function paldex(){let list=catalog.filter(p=>!state.query||p.name.toLowerCase().includes(state.query.toLowerCase())||String(p.number)===state.query),done=Object.values(state.checklist).filter(Boolean).length;head("Tu Paldex","COLECCIÓN",`<div class="toolbar"><input class="search" id="q" placeholder="Buscar por nombre o número..." value="${esc(state.query)}"><select class="select"><option>Todos los elementos</option><option>Fuego</option><option>Agua</option><option>Planta</option></select></div><div class="grid">${list.length?list.map(card).join(""):"<div class='empty'>No hemos encontrado ese Pal.</div>"}</div>`,`<div class="stats"><div class="stat"><b>${done}/${pals.length}</b><small>DESCUBIERTOS</small></div></div>`);document.querySelector("#q").oninput=e=>{state.query=e.target.value;paldex()};document.querySelectorAll("[data-id]").forEach(b=>b.onclick=()=>{state.checklist[b.dataset.id]=!state.checklist[b.dataset.id];save();paldex()})}
function selects(){return catalog.map(p=>`<option value="${p.id}">#${p.number} ${esc(p.name)}</option>`).join("")}
function breeding(){head("Breeding lab","LABORATORIO GENÉTICO",`<div class="two"><section class="panel"><h2>Elige a los padres</h2><p class="sub">Calcula el Pal resultante y revisa las pasivas heredables.</p><div class="parents"><div><label class="label">Padre A</label><select class="select full" id="a">${selects()}</select></div><div><label class="label">Padre B</label><select class="select full" id="b">${selects()}</select></div></div><label class="label">Pasivas objetivo</label><input class="search full" id="wanted" placeholder="Ej: Runner, Legend, Musclehead"><div id="breed"></div></section><section class="panel"><h2>Cómo funciona</h2><p class="sub">La especie se calcula por breeding power. Las pasivas son probabilísticas: el huevo hereda un subconjunto del pool de ambos padres.</p><div class="result"><span class="label">Límite</span><strong>4 pasivas</strong><p class="sub">Para aumentar el control, evita meter rasgos que no quieras conservar.</p></div></section></div>`);let update=()=>{let a=catalog.find(p=>p.id===document.querySelector("#a").value),b=catalog.find(p=>p.id===document.querySelector("#b").value),wanted=document.querySelector("#wanted").value.split(",").map(x=>x.trim()).filter(Boolean),r=calculateBreeding(a,b,{desiredPassives:wanted,combos:datasetCombos,pals:catalog}),i=r.passiveInheritance;document.querySelector("#breed").innerHTML=`<div class="result"><span class="label">Resultado probable · poder ${r.targetPower}</span><strong>${esc(r.child?.name||"Sin datos")}</strong><div class="passives">${i.pool.map(p=>`<span class="passive">${esc(p)}</span>`).join("")||"<span class='sub'>Sin pasivas registradas</span>"}</div>${wanted.length?`<p class="sub" style="margin-top:12px">${i.allDesiredAvailable?"✓ Todas tus pasivas están en el pool":"Faltan: "+i.missing.map(esc).join(", ")}</p>`:""}</div>`};["#a","#b","#wanted"].forEach(id=>document.querySelector(id).oninput=update);update()}
function materialsView(){head("Materiales","MOCHILA Y CRAFTING",`<section class="panel"><h2>Recursos básicos</h2><p class="sub">Una referencia rápida para no volver a la base con las manos vacías.</p><div class="rows">${materials.map(m=>`<div class="row"><div><h3>${esc(m.name)}</h3><p>${esc(m.locations.join(" · "))}</p></div><span class="tag">${esc(m.category)}</span></div>`).join("")}</div></section>`)}
function progress(){head("Mi progreso","RUTA DE SUPERVIVENCIA",`<section class="panel"><h2>Nivel y desbloqueos</h2><p class="sub">Tu hoja de ruta para la próxima sesión.</p><div class="milestones">${levelMilestones.map(m=>`<div class="milestone"><div class="level"><div class="badge">${m.level}</div><div><h3 style="margin:0;font:700 16px 'Space Grotesk'">${esc(m.title)}</h3><p class="sub">${esc(m.unlocks)}</p></div></div></div>`).join("")}</div></section>`)}
function news(){head("Noticias","SEÑAL DE PALWORLD",`<div class="two"><section class="panel"><h2>Fuentes oficiales</h2><p class="sub">Canales oficiales de Pocketpair y Palworld.</p><div class="newslist">${officialNewsSources.map(s=>`<a class="news" href="${s.url}" target="_blank" rel="noreferrer"><div class="source">${s.type==="official-social"?"X / TWITTER":"POCKETPAIR"}</div><h3>${esc(s.name)}</h3><p>${s.handle?esc(s.handle):"Noticias, actualizaciones y anuncios oficiales"}</p></a>`).join("")}</div></section><section class="panel"><h2>Último parte</h2><p class="sub">Las publicaciones se consultan siempre en su fuente original.</p><div class="result"><span class="label">Estado</span><strong>Fuentes listas</strong><p class="sub">Abre una fuente para ver las novedades.</p></div></section></div>`)}
function render(){document.querySelectorAll(".nav").forEach(n=>n.classList.toggle("active",n.dataset.view===state.view));({paldex,breeding,materials:materialsView,progress,news}[state.view])()}document.querySelectorAll(".nav").forEach(n=>n.onclick=()=>{state.view=n.dataset.view;render();document.querySelector(".sidebar").classList.remove("open")});document.querySelector("#menu").onclick=()=>document.querySelector(".sidebar").classList.toggle("open");render(); loadVersionedDataset().then(data=>{catalog=data.pals;datasetCombos=data.combos;render()}).catch(()=>{});




